"""
Django settings for investsite project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from urllib.parse import urlparse, unquote
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-dev-only-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
def _env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}

def _env_list(name: str, default: list[str] | None = None) -> list[str]:
    value = os.environ.get(name)
    if value is None or not value.strip():
        return list(default or [])
    return [item.strip() for item in value.split(',') if item.strip()]


def _build_database_settings() -> dict:
    database_url = os.environ.get('DATABASE_URL') or os.environ.get('DJANGO_DATABASE_URL')
    if database_url:
        parsed = urlparse(database_url)
        scheme = parsed.scheme.lower()
        if scheme in {'postgres', 'postgresql', 'postgresql+psycopg', 'postgresql_psycopg'}:
            return {
                'default': {
                    'ENGINE': 'django.db.backends.postgresql',
                    'NAME': parsed.path.lstrip('/'),
                    'USER': unquote(parsed.username or ''),
                    'PASSWORD': unquote(parsed.password or ''),
                    'HOST': parsed.hostname or '',
                    'PORT': str(parsed.port or ''),
                    'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '60')),
                    'OPTIONS': {
                        'connect_timeout': int(os.environ.get('DB_CONNECT_TIMEOUT', '5')),
                    },
                }
            }
        if scheme == 'sqlite':
            return {
                'default': {
                    'ENGINE': 'django.db.backends.sqlite3',
                    'NAME': parsed.path.lstrip('/') or (BASE_DIR / 'db.sqlite3'),
                    'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '0')),
                }
            }

    postgres_name = os.environ.get('POSTGRES_DB') or os.environ.get('DB_NAME')
    if postgres_name:
        return {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': postgres_name,
                'USER': os.environ.get('POSTGRES_USER') or os.environ.get('DB_USER', ''),
                'PASSWORD': os.environ.get('POSTGRES_PASSWORD') or os.environ.get('DB_PASSWORD', ''),
                'HOST': os.environ.get('POSTGRES_HOST') or os.environ.get('DB_HOST', ''),
                'PORT': os.environ.get('POSTGRES_PORT') or os.environ.get('DB_PORT', '5432'),
                'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '60')),
                'OPTIONS': {
                    'connect_timeout': int(os.environ.get('DB_CONNECT_TIMEOUT', '5')),
                },
            }
        }

    return {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '0')),
        }
    }


DEBUG = _env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS', ['*'] if DEBUG else ['localhost', '127.0.0.1', '[::1]'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'accounts.apps.AccountsConfig',
    'wallets',
    'investments',
    'withdrawals',
    'deposits',
    'payments',
    'settingsconfig',
    'dashboard',
    'users',
    'finance',
    'compliance',
    'adminpanel',
    'kyc',
    'supportchat.apps.SupportChatConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.BrowserFingerprintMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'investments.middleware.InvestmentProfitSyncMiddleware',
    'kyc.middleware.KYCRequiredMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'investsite.urls'
ASGI_APPLICATION = 'investsite.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    }
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'settingsconfig.context_processors.system_settings',
                'wallets.context_processors.wallet_summary',
                'kyc.context_processors.kyc_status',
                'accounts.context_processors.notifications',
            ],
            'builtins': [
                'accounts.templatetags.formatters',
            ],
        },
    },
]

WSGI_APPLICATION = 'investsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = _build_database_settings()


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Use Kenyan time by default across the app and background jobs.
GLOBAL_TIME_ZONE = os.environ.get('DJANGO_TIME_ZONE', 'Africa/Nairobi')
TIME_ZONE = GLOBAL_TIME_ZONE

USE_I18N = True

USE_TZ = True

CSRF_TRUSTED_ORIGINS = _env_list('DJANGO_CSRF_TRUSTED_ORIGINS', [])


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'no-reply@invest.local'
PROJECT_NAME = 'Invest Platform'
PASSWORD_RESET_TIMEOUT = 600

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

REDIS_URL = os.environ.get('REDIS_URL') or os.environ.get('CACHE_URL')

if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }
    SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
    SESSION_CACHE_ALIAS = 'default'
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL],
            },
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'investsite-local',
        }
    }
    SESSION_ENGINE = 'django.contrib.sessions.backends.db'
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        }
    }

# Session hardening
SESSION_COOKIE_AGE = int(os.environ.get('SESSION_COOKIE_AGE', '3600'))
SESSION_SAVE_EVERY_REQUEST = False
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SECURE = not DEBUG
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if _env_bool('DJANGO_SECURE_PROXY_SSL_HEADER', False) else None

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = GLOBAL_TIME_ZONE

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
