# Generated by Django 5.2.12 on 2026-04-06 03:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_seed_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='capital_protection',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='early_withdrawal_fee_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='lock_period_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='management_fee_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='payout_frequency',
            field=models.CharField(blank=True, default='Daily', max_length=20),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='risk_level',
            field=models.CharField(blank=True, default='Moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='auto_reinvest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='goal',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='payout_wallet',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='risk_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='source_funds',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
