# Generated by Django 5.2.12 on 2026-04-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_investmentplan_capital_protection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='liquidity_terms',
            field=models.CharField(blank=True, default='Locked', max_length=40),
        ),
    ]
