# Generated by Django 5.2.12 on 2026-04-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_investmentplan_liquidity_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='plan_tier',
            field=models.CharField(choices=[('standard', 'Standard'), ('starter', 'Starter'), ('basic', 'Basic'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('premium', 'Premium'), ('vip', 'VIP')], default='standard', max_length=20),
        ),
    ]
