# Generated by Django 5.2.12 on 2026-04-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_userinvestment_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinvestment',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='userinvestment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='userinvestment',
            name='payout_wallet',
        ),
        migrations.RemoveField(
            model_name='userinvestment',
            name='source_funds',
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='liquidity_terms',
            field=models.CharField(choices=[('locked', 'Locked'), ('partial', 'Partial'), ('flexible', 'Flexible')], default='locked', max_length=40),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='lock_period_days',
            field=models.IntegerField(choices=[(0, 'No lock'), (7, '7 days'), (14, '14 days'), (30, '30 days'), (60, '60 days'), (90, '90 days'), (180, '180 days')], default=0),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='payout_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('aggressive', 'Aggressive')], default='moderate', max_length=20),
        ),
    ]
