# Generated by Django 5.2.12 on 2026-05-03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_investmentplan_liquidity_terms'),
        ('investments', '0008_remove_bonustracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinvestment',
            name='auto_reinvest',
        ),
    ]
