# Generated by Django 5.2.12 on 2026-05-08 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_investment_accounts(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1])
    InvestmentAccount = apps.get_model('investments', 'InvestmentAccount')
    UserInvestment = apps.get_model('investments', 'UserInvestment')

    accounts = {}
    for user in User.objects.all():
        account, _ = InvestmentAccount.objects.get_or_create(user_id=user.id)
        accounts[user.id] = account.id

    for investment in UserInvestment.objects.filter(account__isnull=True):
        account_id = accounts.get(investment.user_id)
        if account_id:
            investment.account_id = account_id
            investment.save(update_fields=['account'])


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0011_investmentplan_versioning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InvestmentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investment_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='investments.investmentaccount'),
        ),
        migrations.RunPython(backfill_investment_accounts, migrations.RunPython.noop),
    ]
