# Generated by Django 5.2.12 on 2026-05-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0014_profitsyncstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentaccount',
            name='ledger_code',
            field=models.CharField(blank=True, default='', editable=False, max_length=10),
        ),
    ]
