# Generated by Django 5.2.12 on 2026-07-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0015_alter_investmentaccount_ledger_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
