# Generated by Django 5.2.12 on 2026-07-26 16:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0016_userinvestment_activated_at_userinvestment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='reserved_bonus_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='userinvestment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
