# Generated by Django 5.2.12 on 2026-04-06 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('deposit_created', 'Deposit Created'), ('deposit_confirmed', 'Deposit Confirmed'), ('deposit_rejected', 'Deposit Rejected'), ('withdrawal_created', 'Withdrawal Created'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_rejected', 'Withdrawal Rejected'), ('withdrawal_paid', 'Withdrawal Paid'), ('investment_created', 'Investment Created'), ('profit_applied', 'Profit Applied'), ('settings_changed', 'Settings Changed'), ('login', 'Login')], max_length=50)),
                ('target_type', models.CharField(blank=True, default='', max_length=50)),
                ('target_id', models.CharField(blank=True, default='', max_length=50)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
