# Generated by Django 5.2.12 on 2026-04-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('deposit_created', 'Deposit Created'), ('deposit_confirmed', 'Deposit Confirmed'), ('deposit_completed', 'Deposit Completed'), ('deposit_rejected', 'Deposit Rejected'), ('deposit_status_updated', 'Deposit Status Updated'), ('withdrawal_created', 'Withdrawal Created'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_rejected', 'Withdrawal Rejected'), ('withdrawal_paid', 'Withdrawal Paid'), ('withdrawal_completed', 'Withdrawal Completed'), ('withdrawal_status_updated', 'Withdrawal Status Updated'), ('investment_created', 'Investment Created'), ('profit_applied', 'Profit Applied'), ('settings_changed', 'Settings Changed'), ('login', 'Login'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected')], max_length=50),
        ),
    ]
