# Generated by Django 5.2.12 on 2026-04-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0002_deposit_provider_deposit_provider_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='destination_network',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='deposit',
            name='memo_tag',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='deposit',
            name='network',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='deposit',
            name='reference_note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='deposit',
            name='sender_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='deposit',
            name='sender_wallet',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
