# Generated by Django 5.2.12 on 2026-04-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0003_deposit_destination_network_deposit_memo_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='check_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deposit',
            name='confirmations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deposit',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='max_check_attempts',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='deposit',
            name='next_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='target_confirmations',
            field=models.IntegerField(default=3),
        ),
    ]
