# Generated by Codex on 2026-04-06
from django.db import migrations, models
import django.db.models.deletion


def seed_crypto_and_deposits(apps, schema_editor):
    Crypto = apps.get_model('payments', 'CryptoCurrency')
    Deposit = apps.get_model('deposits', 'Deposit')
    defaults = [
        ('Tether', 'USDT', 'TRC20'),
        ('Bitcoin', 'BTC', 'BTC'),
        ('Ethereum', 'ETH', 'ERC20'),
    ]
    symbol_map = {}
    for name, symbol, network in defaults:
        obj, _ = Crypto.objects.get_or_create(
            symbol=symbol,
            network=network,
            defaults={'name': name, 'is_active': True},
        )
        symbol_map[symbol] = obj.id

    default_crypto_id = symbol_map.get('USDT')
    for deposit in Deposit.objects.all():
        sym = getattr(deposit, 'crypto_type', '') or ''
        if sym in symbol_map:
            deposit.crypto_id = symbol_map[sym]
        elif default_crypto_id:
            deposit.crypto_id = default_crypto_id
        if deposit.status == 'confirmed':
            deposit.status = 'completed'
            if getattr(deposit, 'confirmed_at', None):
                deposit.completed_at = deposit.confirmed_at
        deposit.save(update_fields=['crypto', 'status', 'completed_at'])


def reverse_seed_crypto_and_deposits(apps, schema_editor):
    # No-op reverse
    return


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('deposits', '0005_deposit_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='crypto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.cryptocurrency'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='method',
            field=models.CharField(choices=[('manual', 'Manual'), ('automated', 'Automated')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='deposit',
            name='sender_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='pay_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirming', 'Confirming'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.RunPython(seed_crypto_and_deposits, reverse_seed_crypto_and_deposits),
        migrations.RemoveField(
            model_name='deposit',
            name='crypto_type',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='wallet_address',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='sender_name',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='sender_wallet',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='network',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='memo_tag',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='destination_network',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='reference_note',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='confirmed_at',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='crypto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.cryptocurrency'),
        ),
    ]
