# Generated by Django 5.2.12 on 2026-07-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0008_deposit_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='screenshot',
            field=models.FileField(blank=True, null=True, upload_to='deposits/screenshots/'),
        ),
    ]
