# Generated by Django 5.2.12 on 2026-07-26 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0009_deposit_screenshot'),
        ('investments', '0016_userinvestment_activated_at_userinvestment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='investment_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_deposits', to='investments.userinvestment'),
        ),
    ]
