# Generated by Django 5.2.12 on 2026-04-22 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_two_factor_code_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='two_factor_code_expires_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='two_factor_email_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='two_factor_enabled',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='two_factor_last_sent_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='two_factor_method',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='two_factor_secret',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='two_factor_verified',
        ),
    ]
