# Generated by Django 5.2.12 on 2026-04-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='beneficiary_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='destination_network',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='memo_tag',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='purpose',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='reference_note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
