# Generated by Codex on 2026-04-06
from django.db import migrations, models
import django.db.models.deletion


def seed_crypto_and_withdrawals(apps, schema_editor):
    Crypto = apps.get_model('payments', 'CryptoCurrency')
    Withdrawal = apps.get_model('withdrawals', 'Withdrawal')
    defaults = [
        ('Tether', 'USDT', 'TRC20'),
        ('Bitcoin', 'BTC', 'BTC'),
        ('Ethereum', 'ETH', 'ERC20'),
    ]
    symbol_map = {}
    for name, symbol, network in defaults:
        obj, _ = Crypto.objects.get_or_create(
            symbol=symbol,
            network=network,
            defaults={'name': name, 'is_active': True},
        )
        symbol_map[symbol] = obj.id

    default_crypto_id = symbol_map.get('USDT')
    for withdrawal in Withdrawal.objects.all():
        sym = getattr(withdrawal, 'crypto_type', '') or ''
        if sym in symbol_map:
            withdrawal.crypto_id = symbol_map[sym]
        elif default_crypto_id:
            withdrawal.crypto_id = default_crypto_id
        if withdrawal.status == 'paid':
            withdrawal.status = 'completed'
        if withdrawal.status == 'cooldown':
            withdrawal.status = 'pending'
        withdrawal.save(update_fields=['crypto', 'status'])


def reverse_seed_crypto_and_withdrawals(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('withdrawals', '0004_withdrawal_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='crypto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.cryptocurrency'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='method',
            field=models.CharField(choices=[('manual', 'Manual'), ('automated', 'Automated')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.RunPython(seed_crypto_and_withdrawals, reverse_seed_crypto_and_withdrawals),
        migrations.RemoveField(
            model_name='withdrawal',
            name='beneficiary_name',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='reference_note',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='cooldown_until',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='note',
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='crypto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.cryptocurrency'),
        ),
    ]
