# Generated by Django 5.2.12 on 2026-04-06 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_alter_transaction_txn_type_alter_wallet_created_at'),
        ('wallets', '0003_wallet_approval_fields'),
    ]

    operations = [
    ]
