# Generated by Django 5.2.12 on 2026-04-06 13:29

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_alter_transaction_wallet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='is_primary',
            new_name='is_default',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='address',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(choices=[('primary', 'Primary'), ('trading', 'Trading'), ('savings', 'Savings')], default=1234, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(condition=models.Q(('wallet_type', 'primary')), fields=('user',), name='uniq_primary_wallet_per_user'),
        ),
    ]
