# Generated by Django 5.2.12 on 2026-04-06 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_submitted', max_length=20)),
                ('full_name', models.CharField(blank=True, default='', max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=80)),
                ('id_type', models.CharField(blank=True, choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('drivers_license', 'Driver License')], default='', max_length=30)),
                ('id_number', models.CharField(blank=True, default='', max_length=60)),
                ('address_line', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=80)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('phone_number', models.CharField(blank=True, default='', max_length=40)),
                ('occupation', models.CharField(blank=True, default='', max_length=100)),
                ('source_of_funds', models.CharField(blank=True, default='', max_length=120)),
                ('tax_id', models.CharField(blank=True, default='', max_length=60)),
                ('id_document_front', models.FileField(blank=True, null=True, upload_to='kyc/')),
                ('id_document_back', models.FileField(blank=True, null=True, upload_to='kyc/')),
                ('selfie_photo', models.FileField(blank=True, null=True, upload_to='kyc/')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
