# Generated by Django 5.2.12 on 2026-04-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycprofile',
            name='source_of_funds_other',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
