# Generated by Django 5.2.12 on 2026-04-06 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_kycprofile_source_of_funds_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycprofile',
            name='occupation',
        ),
    ]
