# Generated by Django 5.2.12 on 2026-04-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_remove_kycprofile_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycprofile',
            name='country_of_residence',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
