# Generated by Django 5.2.12 on 2026-05-16 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_kycprofile_country_of_residence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kycprofile',
            name='revocation_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_revocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='verification_method',
            field=models.CharField(choices=[('manual', 'Manual'), ('automated', 'Automated')], default='manual', max_length=20),
        ),
    ]
