# Generated by Django 5.2.12 on 2026-05-16 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_kycprofile_revocation_note_kycprofile_revoked_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCVerificationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('verified', 'Verified'), ('manual_review', 'Manual Review'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('current_stage', models.CharField(blank=True, default='queued', max_length=40)),
                ('stage_label', models.CharField(blank=True, default='Queued', max_length=120)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('stage_log', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_runs', to='kyc.kycprofile')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='KYCVerificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_key', models.CharField(max_length=40)),
                ('stage_label', models.CharField(max_length=120)),
                ('status', models.CharField(blank=True, default='', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('percent', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='kyc.kycverificationrun')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
